In [1]:
import pandas as pd 
import numpy as np 
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
data=pd.read_csv("../../Data/final_data.csv")
data.head()

,useridx,continent,region,usercountry,usercity,transactionid,visityearx,visitmonthx,attractionidx,ratingx,visitmodex,attraction,attractionaddress,attractiontype,attractioncity,attractioncountry
0,14,Europe,Southern Europe,Portugal,Lagos,5661,2018,12,640,4,Friends,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Douala,Cameroon
1,14,Europe,Southern Europe,Portugal,Lagos,67652,2018,12,748,5,Friends,Tegalalang Rice Terrace,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",Points of Interest & Landmarks,Douala,Cameroon
2,14,Europe,Southern Europe,Portugal,Lagos,68777,2018,12,748,5,Friends,Tegalalang Rice Terrace,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",Points of Interest & Landmarks,Douala,Cameroon
3,16,Asia,South East Asia,Indonesia,Jakarta,4735,2018,4,640,5,Family,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Douala,Cameroon
4,16,Asia,South East Asia,Indonesia,Jakarta,5318,2017,12,640,5,Friends,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas,Douala,Cameroon

In [3]:
data.shape

(52930, 16)

In [4]:
data.duplicated(subset=["useridx","attractionidx","ratingx"]).sum()

np.int64(5433)

In [5]:
data=data.drop_duplicates(subset=["useridx","attractionidx","ratingx"],keep="first")
data.info()

<class 'pandas.DataFrame'>
Index: 47497 entries, 0 to 52929
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   useridx            47497 non-null  int64
 1   continent          47497 non-null  str
 2   region             47497 non-null  str
 3   usercountry        47497 non-null  str
 4   usercity           47489 non-null  str
 5   transactionid      47497 non-null  int64
 6   visityearx         47497 non-null  int64
 7   visitmonthx        47497 non-null  int64
 8   attractionidx      47497 non-null  int64
 9   ratingx            47497 non-null  int64
 10  visitmodex         47497 non-null  str
 11  attraction         47497 non-null  str
 12  attractionaddress  47497 non-null  str
 13  attractiontype     47497 non-null  str
 14  attractioncity     47497 non-null  str
 15  attractioncountry  47497 non-null  str
dtypes: int64(6), str(10)
memory usage: 12.2 MB

In [6]:
data.dropna(inplace=True)

In [7]:
data.describe()

,useridx,transactionid,visityearx,visitmonthx,attractionidx,ratingx
count,47489.000000,47489.000000,47489.000000,47489.000000,47489.000000,47489.000000
mean,44875.275853,66362.357220,2016.350165,6.606814,743.324180,4.145992
std,25113.407434,62342.320923,1.738689,3.382891,196.679142,0.981711
min,14.000000,3.000000,2013.000000,1.000000,369.000000,1.000000
25%,23322.000000,18956.000000,2015.000000,4.000000,640.000000,4.000000
50%,45293.000000,42279.000000,2016.000000,7.000000,737.000000,4.000000
75%,66579.000000,100733.000000,2018.000000,9.000000,824.000000,5.000000
max,88190.000000,211239.000000,2022.000000,12.000000,1297.000000,5.000000

In [8]:
data.isna().sum()

useridx              0
continent            0
region               0
usercountry          0
usercity             0
transactionid        0
visityearx           0
visitmonthx          0
attractionidx        0
ratingx              0
visitmodex           0
attraction           0
attractionaddress    0
attractiontype       0
attractioncity       0
attractioncountry    0
dtype: int64

In [9]:
data=data.loc[:,["useridx","transactionid","ratingx","attraction","attractionidx","attractionaddress","attractioncity"]]
data.head()

,useridx,transactionid,ratingx,attraction,attractionidx,attractionaddress,attractioncity
0,14,5661,4,Sacred Monkey Forest Sanctuary,640,"Jl. Monkey Forest, Ubud 80571 Indonesia",Douala
1,14,67652,5,Tegalalang Rice Terrace,748,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",Douala
3,16,4735,5,Sacred Monkey Forest Sanctuary,640,"Jl. Monkey Forest, Ubud 80571 Indonesia",Douala
5,16,12109,3,Sacred Monkey Forest Sanctuary,640,"Jl. Monkey Forest, Ubud 80571 Indonesia",Douala
6,16,14015,4,Sacred Monkey Forest Sanctuary,640,"Jl. Monkey Forest, Ubud 80571 Indonesia",Douala

In [10]:
user_attraction_interaction=data.groupby("useridx")["attractionidx"].nunique()
user_attraction_interaction

useridx
14       2
16       5
20       1
23       1
25       1
        ..
88179    1
88185    5
88187    1
88189    2
88190    1
Name: attractionidx, Length: 33526, dtype: int64

In [11]:
data["user_attraction_interaction"]=data.useridx.map(user_attraction_interaction)
data.head(2)

,useridx,transactionid,ratingx,attraction,attractionidx,attractionaddress,attractioncity,user_attraction_interaction
0,14,5661,4,Sacred Monkey Forest Sanctuary,640,"Jl. Monkey Forest, Ubud 80571 Indonesia",Douala,2
1,14,67652,5,Tegalalang Rice Terrace,748,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",Douala,2

In [12]:
transaction_per_attraction=data.groupby("attractionidx")["transactionid"].nunique()
transaction_per_attraction

attractionidx
369      2617
481      2005
640     11878
650      2875
673      2798
737      3177
748      5515
749      2170
824      3203
841      5726
877        36
888       381
897        54
913        52
920        43
928        28
937        64
947        83
949        31
975        53
1133      127
1137      104
1166      795
1171     1327
1220      297
1225      180
1238      260
1278      665
1280      307
1297      638
Name: transactionid, dtype: int64

In [13]:
data["transaction_per_attraction"]=data.attractionidx.map(transaction_per_attraction)
data.head(2)

,useridx,transactionid,ratingx,attraction,attractionidx,attractionaddress,attractioncity,user_attraction_interaction,transaction_per_attraction
0,14,5661,4,Sacred Monkey Forest Sanctuary,640,"Jl. Monkey Forest, Ubud 80571 Indonesia",Douala,2,11878
1,14,67652,5,Tegalalang Rice Terrace,748,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",Douala,2,5515

In [14]:
rating_per_attraction=data.groupby("attractionidx")["ratingx"].mean()
rating_per_attraction

attractionidx
369     3.404280
481     4.269327
640     4.255599
650     3.966609
673     3.802001
737     4.197671
748     4.153037
749     3.894009
824     4.214799
841     4.637967
877     4.027778
888     4.611549
897     3.981481
913     4.096154
920     4.302326
928     4.571429
937     3.578125
947     4.698795
949     4.032258
975     4.207547
1133    4.496063
1137    3.788462
1166    3.763522
1171    4.023361
1220    4.168350
1225    3.872222
1238    4.103846
1278    4.201504
1280    3.785016
1297    3.478056
Name: ratingx, dtype: float64

In [ ]:
data["rating_per_attraction"]=data.attractionidx.map(rating_per_attraction)
data.head(2)

,useridx,transactionid,ratingx,attraction,attractionidx,attractionaddress,attractioncity,user_attraction_interaction,transaction_per_attraction,rating_per_attraction
0,14,5661,4,Sacred Monkey Forest Sanctuary,640,"Jl. Monkey Forest, Ubud 80571 Indonesia",Douala,2,11878,4.255599
1,14,67652,5,Tegalalang Rice Terrace,748,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",Douala,2,5515,4.153037

In [16]:
data["interaction_metrics"]=data.user_attraction_interaction*data.transaction_per_attraction*data.rating_per_attraction
data.head()

,useridx,transactionid,ratingx,attraction,attractionidx,attractionaddress,attractioncity,user_attraction_interaction,transaction_per_attraction,rating_per_attraction,interaction_metrics
0,14,5661,4,Sacred Monkey Forest Sanctuary,640,"Jl. Monkey Forest, Ubud 80571 Indonesia",Douala,2,11878,4.255599,101096.0
1,14,67652,5,Tegalalang Rice Terrace,748,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",Douala,2,5515,4.153037,45808.0
3,16,4735,5,Sacred Monkey Forest Sanctuary,640,"Jl. Monkey Forest, Ubud 80571 Indonesia",Douala,5,11878,4.255599,252740.0
5,16,12109,3,Sacred Monkey Forest Sanctuary,640,"Jl. Monkey Forest, Ubud 80571 Indonesia",Douala,5,11878,4.255599,252740.0
6,16,14015,4,Sacred Monkey Forest Sanctuary,640,"Jl. Monkey Forest, Ubud 80571 Indonesia",Douala,5,11878,4.255599,252740.0

In [17]:
user_attraction_matrix=pd.pivot_table(
    data=data,
    index="useridx",
    columns="attraction",
    values="interaction_metrics",
    fill_value=0,
    aggfunc="mean",
)
user_attraction_matrix

attraction,Balekambang Beach,Bromo Tengger Semeru National Park,Coban Rondo Waterfall,Goa Cina Beach,Jodipan Colorful Village,Jomblang Cave,Kalibiru National Park,Khayangan Reflexology & Massage,Kuta Beach - Bali,Malang City Square,...,Sempu Island,Sewu Temple,Tanah Lot Temple,Tegalalang Rice Terrace,Tegenungan Waterfall,Ullen Sentalu Museum,Uluwatu Temple,Water Castle (Tamansari),Waterbom Bali,Yogyakarta Palace
useridx,,,,,,,,,,,,,,,,,,,,,
14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,45808.0,0.0,0.0,0.0,0.0,0.0,0.0
16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,114520.0,0.0,0.0,67500.0,0.0,132785.0,0.0
20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,26557.0,0.0
23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,22904.0,0.0,0.0,0.0,0.0,0.0,0.0
25,0.0,1757.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88179,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,22904.0,0.0,0.0,0.0,0.0,0.0,0.0
88185,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,44545.0,0.0,...,0.0,0.0,66680.0,114520.0,0.0,0.0,67500.0,0.0,132785.0,0.0
88187,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,13500.0,0.0,0.0,0.0
88189,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
88190,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,22904.0,0.0,0.0,0.0,0.0,0.0,0.0

In [18]:
attraction_user_matrix=user_attraction_matrix.T
attraction_user_matrix

useridx,14,16,20,23,25,26,27,28,29,32,...,88168,88170,88175,88177,88178,88179,88185,88187,88189,88190
attraction,,,,,,,,,,,,,,,,,,,,,
Balekambang Beach,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Bromo Tengger Semeru National Park,0.0,0.0,0.0,0.0,1757.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Coban Rondo Waterfall,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Goa Cina Beach,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Jodipan Colorful Village,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Jomblang Cave,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kalibiru National Park,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Khayangan Reflexology & Massage,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kuta Beach - Bali,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,26727.0,0.0,0.0,0.0,0.0,44545.0,0.0,0.0,0.0
Malang City Square,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Malioboro Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Merapi Volcano,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Mount Semeru Volcano,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Museum Malang Tempo Doeloe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Nusa Dua Beach,0.0,42800.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Ramayana Ballet at Prambanan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Ratu Boko Temple,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Sacred Monkey Forest Sanctuary,101096.0,252740.0,0.0,0.0,0.0,0.0,50548.0,0.0,50548.0,50548.0,...,50548.0,151644.0,50548.0,50548.0,50548.0,0.0,0.0,0.0,101096.0,0.0
Sanur Beach,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22808.0,0.0
Seminyak Beach,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,31914.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Sempu Island,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Sewu Temple,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Tanah Lot Temple,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,66680.0,0.0,0.0,0.0
Tegalalang Rice Terrace,45808.0,114520.0,0.0,22904.0,0.0,22904.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,22904.0,114520.0,0.0,0.0,22904.0
Tegenungan Waterfall,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8450.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Ullen Sentalu Museum,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Uluwatu Temple,0.0,67500.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,67500.0,13500.0,0.0,0.0
Water Castle (Tamansari),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Waterbom Bali,0.0,132785.0,26557.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,132785.0,0.0,0.0,0.0
Yogyakarta Palace,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
attraction_attraction_similarity=cosine_similarity(attraction_user_matrix)
attraction_attraction_similarity

array([[1.        , 0.09685455, 0.38576884, 0.53813824, 0.        ,
        0.        , 0.        , 0.        , 0.00934367, 0.30638305,
        0.02444709, 0.        , 0.1391832 , 0.2869149 , 0.        ,
        0.        , 0.        , 0.00116733, 0.03183609, 0.        ,
        0.31467259, 0.        , 0.02168904, 0.01818786, 0.        ,
        0.        , 0.01146659, 0.0453478 , 0.00551638, 0.        ],
       [0.09685455, 1.        , 0.18913298, 0.1311435 , 0.20125798,
        0.        , 0.04301881, 0.04533051, 0.029222  , 0.24657548,
        0.07428533, 0.10682856, 0.24106536, 0.08847663, 0.02817584,
        0.06124001, 0.04281   , 0.04094688, 0.04095422, 0.04566071,
        0.11414644, 0.05754826, 0.04171839, 0.05205886, 0.04701058,
        0.05931643, 0.04166438, 0.03384428, 0.02117327, 0.06904399],
       [0.38576884, 0.18913298, 1.        , 0.34265758, 0.13461909,
        0.        , 0.        , 0.04958019, 0.01764879, 0.23153016,
        0.03674441, 0.01021584, 0.        , 0.05856603, 0.        ,
        0.02022074, 0.        , 0.01210013, 0.02423617, 0.        ,
        0.07498351, 0.02055293, 0.01247985, 0.02871439, 0.01673118,
        0.04303634, 0.02244049, 0.03760472, 0.00140753, 0.01357605],
       [0.53813824, 0.1311435 , 0.34265758, 1.        , 0.        ,
        0.        , 0.        , 0.05228407, 0.0040854 , 0.31545915,
        0.03607598, 0.        , 0.17139062, 0.30107977, 0.        ,
        0.        , 0.        , 0.00969761, 0.01643007, 0.        ,
        0.34159431, 0.        , 0.02245016, 0.01590482, 0.        ,
        0.021784  , 0.01363705, 0.        , 0.00333965, 0.        ],
       [0.        , 0.20125798, 0.13461909, 0.        , 1.        ,
        0.15958914, 0.        , 0.        , 0.        , 0.26484462,
        0.06456629, 0.0239833 , 0.        , 0.        , 0.00572743,
        0.05584871, 0.        , 0.00481248, 0.        , 0.01891688,
        0.        , 0.04541296, 0.02372261, 0.        , 0.02637392,
        0.02781425, 0.01701812, 0.05842262, 0.00699755, 0.0374964 ],
       [0.        , 0.        , 0.        , 0.        , 0.15958914,
        1.        , 0.        , 0.        , 0.00975245, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.01404968, 0.        , 0.02693975,
        0.        , 0.        , 0.02286892, 0.        , 0.02080213,
        0.        , 0.01938856, 0.        , 0.00996529, 0.        ],
       [0.        , 0.04301881, 0.        , 0.        , 0.        ,
        0.        , 1.        , 0.        , 0.00929156, 0.        ,
        0.        , 0.        , 0.06257643, 0.        , 0.        ,
        0.        , 0.        , 0.0036164 , 0.00287442, 0.        ,
        0.        , 0.        , 0.00548513, 0.01637409, 0.00609817,
        0.        , 0.01136755, 0.        , 0.00467413, 0.        ],
       [0.        , 0.04533051, 0.04958019, 0.05228407, 0.        ,
        0.        , 0.        , 1.        , 0.        , 0.01792443,
        0.01108433, 0.00992996, 0.08242387, 0.        , 0.        ,
        0.07861957, 0.        , 0.00211707, 0.        , 0.        ,
        0.        , 0.        , 0.0104359 , 0.        , 0.        ,
        0.03011906, 0.00748651, 0.        , 0.        , 0.01319615],
       [0.00934367, 0.029222  , 0.01764879, 0.0040854 , 0.        ,
        0.00975245, 0.00929156, 0.        , 1.        , 0.01190501,
        0.09657167, 0.06575862, 0.00644048, 0.        , 0.22093842,
        0.01766176, 0.01879774, 0.29445683, 0.24998515, 0.26826561,
        0.01845227, 0.00468311, 0.27010091, 0.29848789, 0.20872335,
        0.00970802, 0.23587885, 0.03534489, 0.31931064, 0.0314494 ],
       [0.30638305, 0.24657548, 0.23153016, 0.31545915, 0.26484462,
        0.        , 0.        , 0.01792443, 0.01190501, 1.        ,
        0.05565532, 0.04893582, 0.27015659, 0.18460231, 0.        ,
        0.12427478, 0.        , 0.02165371, 0.04752578, 0.03370266,
        0.20249927, 0.0297215 , 0.05732595, 0.02288525, 0.01062215,
        0.01680336, 0.02846347, 0.00764719, 0.        , 0.09079925],
       [0.02444709, 0.07428533, 0.03674441, 0.03607598, 0.06456629,
        0.        , 0.        , 0.01108433, 0.09657167, 0.05565532,
        1.        , 0.        , 0.0308059 , 0.        , 0.03914854,
        0.        , 0.        , 0.06001374, 0.08076693, 0.0625244 ,
        0.00603489, 0.        , 0.08825556, 0.08855984, 0.06445493,
        0.        , 0.06772788, 0.        , 0.03009054, 0.        ],
       [0.        , 0.10682856, 0.01021584, 0.        , 0.0239833 ,
        0.        , 0.        , 0.00992996, 0.06575862, 0.04893582,
        0.        , 1.        , 0.03078199, 0.00659793, 0.05791404,
        0.        , 0.        , 0.0508192 , 0.05519303, 0.06973028,
        0.10272146, 0.        , 0.08667295, 0.05489534, 0.03733023,
        0.        , 0.09203999, 0.        , 0.03805663, 0.        ],
       [0.1391832 , 0.24106536, 0.        , 0.17139062, 0.        ,
        0.        , 0.06257643, 0.08242387, 0.00644048, 0.27015659,
        0.0308059 , 0.03078199, 1.        , 0.33886627, 0.        ,
        0.06723134, 0.0444805 , 0.02127234, 0.00364238, 0.01937233,
        0.31132646, 0.01921945, 0.03672667, 0.022783  , 0.02327769,
        0.02575625, 0.00142268, 0.01978027, 0.01184587, 0.07476083],
       [0.2869149 , 0.08847663, 0.05856603, 0.30107977, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.18460231,
        0.        , 0.00659793, 0.33886627, 1.        , 0.00297622,
        0.        , 0.06912237, 0.        , 0.        , 0.        ,
        0.32253272, 0.02986689, 0.02613622, 0.        , 0.        ,
        0.05253284, 0.        , 0.05464603, 0.        , 0.        ],
       [0.        , 0.02817584, 0.        , 0.        , 0.00572743,
        0.        , 0.        , 0.        , 0.22093842, 0.        ,
        0.03914854, 0.05791404, 0.        , 0.00297622, 1.        ,
        0.00593713, 0.00241725, 0.26327819, 0.21210547, 0.24260965,
        0.        , 0.01903241, 0.22622383, 0.25004108, 0.16830751,
        0.02484462, 0.22111856, 0.00429975, 0.22609997, 0.01809096],
       [0.        , 0.06124001, 0.02022074, 0.        , 0.05584871,
        0.        , 0.        , 0.07861957, 0.01766176, 0.12427478,
        0.        , 0.        , 0.06723134, 0.        , 0.00593713,
        1.        , 0.        , 0.02482349, 0.02045958, 0.00301685,
        0.        , 0.        , 0.03568633, 0.01888566, 0.00145595,
        0.        , 0.01865899, 0.        , 0.00125546, 0.        ],
       [0.        , 0.04281   , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.01879774, 0.        ,
        0.        , 0.        , 0.0444805 , 0.06912237, 0.00241725,
        0.        , 1.        , 0.01199616, 0.00664037, 0.        ,
        0.        , 0.        , 0.01342966, 0.00445021, 0.00626122,
        0.        , 0.02109848, 0.        , 0.00166123, 0.        ],
       [0.00116733, 0.04094688, 0.01210013, 0.00969761, 0.00481248,
        0.01404968, 0.0036164 , 0.00211707, 0.29445683, 0.02165371,
        0.06001374, 0.0508192 , 0.02127234, 0.        , 0.26327819,
        0.02482349, 0.01199616, 1.        , 0.32453335, 0.3266578 ,
        0.00518691, 0.03620142, 0.35095489, 0.57707732, 0.3977063 ,
        0.01769659, 0.32997322, 0.01603213, 0.38540082, 0.04347732],
       [0.03183609, 0.04095422, 0.02423617, 0.01643007, 0.        ,
        0.        , 0.00287442, 0.        , 0.24998515, 0.04752578,
        0.08076693, 0.05519303, 0.00364238, 0.        , 0.21210547,
        0.02045958, 0.00664037, 0.32453335, 1.        , 0.28555376,
        0.        , 0.05022357, 0.24211122, 0.29472167, 0.20817055,
        0.0070986 , 0.22101433, 0.00161528, 0.28857259, 0.03758074],
       [0.        , 0.04566071, 0.        , 0.        , 0.01891688,
        0.02693975, 0.        , 0.        , 0.26826561, 0.03370266,
        0.0625244 , 0.06973028, 0.01937233, 0.        , 0.24260965,
        0.00301685, 0.        , 0.3266578 , 0.28555376, 1.        ,
        0.        , 0.02223147, 0.29756816, 0.30236729, 0.23246816,
        0.0283159 , 0.24648424, 0.01854083, 0.28975686, 0.04810536],
       [0.31467259, 0.11414644, 0.07498351, 0.34159431, 0.        ,
        0.        , 0.        , 0.        , 0.01845227, 0.20249927,
        0.00603489, 0.10272146, 0.31132646, 0.32253272, 0.        ,
        0.        , 0.        , 0.00518691, 0.        , 0.        ,
        1.        , 0.        , 0.03715058, 0.00690734, 0.        ,
        0.0184482 , 0.01630419, 0.        , 0.00670399, 0.        ],
       [0.        , 0.05754826, 0.02055293, 0.        , 0.04541296,
        0.        , 0.        , 0.        , 0.00468311, 0.0297215 ,
        0.        , 0.        , 0.01921945, 0.02986689, 0.01903241,
        0.        , 0.        , 0.03620142, 0.05022357, 0.02223147,
        0.        , 1.        , 0.01963379, 0.04365099, 0.01257892,
        0.        , 0.04068966, 0.        , 0.03094501, 0.        ],
       [0.02168904, 0.04171839, 0.01247985, 0.02245016, 0.02372261,
        0.02286892, 0.00548513, 0.0104359 , 0.27010091, 0.05732595,
        0.08825556, 0.08667295, 0.03672667, 0.02613622, 0.22622383,
        0.03568633, 0.01342966, 0.35095489, 0.24211122, 0.29756816,
        0.03715058, 0.01963379, 1.        , 0.34907015, 0.24844602,
        0.02358001, 0.44478114, 0.02294658, 0.24920366, 0.04923794],
       [0.01818786, 0.05205886, 0.02871439, 0.01590482, 0.        ,
        0.        , 0.01637409, 0.        , 0.29848789, 0.02288525,
        0.08855984, 0.05489534, 0.022783  , 0.        , 0.25004108,
        0.01888566, 0.00445021, 0.57707732, 0.29472167, 0.30236729,
        0.00690734, 0.04365099, 0.34907015, 1.        , 0.42830606,
        0.03667092, 0.32483555, 0.02165046, 0.30182143, 0.03265454],
       [0.        , 0.04701058, 0.01673118, 0.        , 0.02637392,
        0.02080213, 0.00609817, 0.        , 0.20872335, 0.01062215,
        0.06445493, 0.03733023, 0.02327769, 0.        , 0.16830751,
        0.00145595, 0.00626122, 0.3977063 , 0.20817055, 0.23246816,
        0.        , 0.01257892, 0.24844602, 0.42830606, 1.        ,
        0.02398429, 0.2290989 , 0.00152305, 0.22688904, 0.02419354],
       [0.        , 0.05931643, 0.04303634, 0.021784  , 0.02781425,
        0.        , 0.        , 0.03011906, 0.00970802, 0.01680336,
        0.        , 0.        , 0.02575625, 0.05253284, 0.02484462,
        0.        , 0.        , 0.01769659, 0.0070986 , 0.0283159 ,
        0.0184482 , 0.        , 0.02358001, 0.03667092, 0.02398429,
        1.        , 0.01689583, 0.        , 0.00577157, 0.        ],
       [0.01146659, 0.04166438, 0.02244049, 0.01363705, 0.01701812,
        0.01938856, 0.01136755, 0.00748651, 0.23587885, 0.02846347,
        0.06772788, 0.09203999, 0.00142268, 0.        , 0.22111856,
        0.01865899, 0.02109848, 0.32997322, 0.22101433, 0.24648424,
        0.01630419, 0.04068966, 0.44478114, 0.32483555, 0.2290989 ,
        0.01689583, 1.        , 0.01597003, 0.25094937, 0.03416592],
       [0.0453478 , 0.03384428, 0.03760472, 0.        , 0.05842262,
        0.        , 0.        , 0.        , 0.03534489, 0.00764719,
        0.        , 0.        , 0.01978027, 0.05464603, 0.00429975,
        0.        , 0.        , 0.01603213, 0.00161528, 0.01854083,
        0.        , 0.        , 0.02294658, 0.02165046, 0.00152305,
        0.        , 0.01597003, 1.        , 0.00656659, 0.        ],
       [0.00551638, 0.02117327, 0.00140753, 0.00333965, 0.00699755,
        0.00996529, 0.00467413, 0.        , 0.31931064, 0.        ,
        0.03009054, 0.03805663, 0.01184587, 0.        , 0.22609997,
        0.00125546, 0.00166123, 0.38540082, 0.28857259, 0.28975686,
        0.00670399, 0.03094501, 0.24920366, 0.30182143, 0.22688904,
        0.00577157, 0.25094937, 0.00656659, 1.        , 0.02655151],
       [0.        , 0.06904399, 0.01357605, 0.        , 0.0374964 ,
        0.        , 0.        , 0.01319615, 0.0314494 , 0.09079925,
        0.        , 0.        , 0.07476083, 0.        , 0.01809096,
        0.        , 0.        , 0.04347732, 0.03758074, 0.04810536,
        0.        , 0.        , 0.04923794, 0.03265454, 0.02419354,
        0.        , 0.03416592, 0.        , 0.02655151, 1.        ]])

In [20]:
attraction_attraction_similarity_df=pd.DataFrame(
    index=attraction_user_matrix.index.str.lower(),
    columns=attraction_user_matrix.index.str.lower(),
    data=attraction_attraction_similarity
)
attraction_attraction_similarity_df

attraction,balekambang beach,bromo tengger semeru national park,coban rondo waterfall,goa cina beach,jodipan colorful village,jomblang cave,kalibiru national park,khayangan reflexology & massage,kuta beach - bali,malang city square,...,sempu island,sewu temple,tanah lot temple,tegalalang rice terrace,tegenungan waterfall,ullen sentalu museum,uluwatu temple,water castle (tamansari),waterbom bali,yogyakarta palace
attraction,,,,,,,,,,,,,,,,,,,,,
balekambang beach,1.000000,0.096855,0.385769,0.538138,0.000000,0.000000,0.000000,0.000000,0.009344,0.306383,...,0.314673,0.000000,0.021689,0.018188,0.000000,0.000000,0.011467,0.045348,0.005516,0.000000
bromo tengger semeru national park,0.096855,1.000000,0.189133,0.131144,0.201258,0.000000,0.043019,0.045331,0.029222,0.246575,...,0.114146,0.057548,0.041718,0.052059,0.047011,0.059316,0.041664,0.033844,0.021173,0.069044
coban rondo waterfall,0.385769,0.189133,1.000000,0.342658,0.134619,0.000000,0.000000,0.049580,0.017649,0.231530,...,0.074984,0.020553,0.012480,0.028714,0.016731,0.043036,0.022440,0.037605,0.001408,0.013576
goa cina beach,0.538138,0.131144,0.342658,1.000000,0.000000,0.000000,0.000000,0.052284,0.004085,0.315459,...,0.341594,0.000000,0.022450,0.015905,0.000000,0.021784,0.013637,0.000000,0.003340,0.000000
jodipan colorful village,0.000000,0.201258,0.134619,0.000000,1.000000,0.159589,0.000000,0.000000,0.000000,0.264845,...,0.000000,0.045413,0.023723,0.000000,0.026374,0.027814,0.017018,0.058423,0.006998,0.037496
jomblang cave,0.000000,0.000000,0.000000,0.000000,0.159589,1.000000,0.000000,0.000000,0.009752,0.000000,...,0.000000,0.000000,0.022869,0.000000,0.020802,0.000000,0.019389,0.000000,0.009965,0.000000
kalibiru national park,0.000000,0.043019,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.009292,0.000000,...,0.000000,0.000000,0.005485,0.016374,0.006098,0.000000,0.011368,0.000000,0.004674,0.000000
khayangan reflexology & massage,0.000000,0.045331,0.049580,0.052284,0.000000,0.000000,0.000000,1.000000,0.000000,0.017924,...,0.000000,0.000000,0.010436,0.000000,0.000000,0.030119,0.007487,0.000000,0.000000,0.013196
kuta beach - bali,0.009344,0.029222,0.017649,0.004085,0.000000,0.009752,0.009292,0.000000,1.000000,0.011905,...,0.018452,0.004683,0.270101,0.298488,0.208723,0.009708,0.235879,0.035345,0.319311,0.031449
malang city square,0.306383,0.246575,0.231530,0.315459,0.264845,0.000000,0.000000,0.017924,0.011905,1.000000,...,0.202499,0.029722,0.057326,0.022885,0.010622,0.016803,0.028463,0.007647,0.000000,0.090799
malioboro road,0.024447,0.074285,0.036744,0.036076,0.064566,0.000000,0.000000,0.011084,0.096572,0.055655,...,0.006035,0.000000,0.088256,0.088560,0.064455,0.000000,0.067728,0.000000,0.030091,0.000000
merapi volcano,0.000000,0.106829,0.010216,0.000000,0.023983,0.000000,0.000000,0.009930,0.065759,0.048936,...,0.102721,0.000000,0.086673,0.054895,0.037330,0.000000,0.092040,0.000000,0.038057,0.000000
mount semeru volcano,0.139183,0.241065,0.000000,0.171391,0.000000,0.000000,0.062576,0.082424,0.006440,0.270157,...,0.311326,0.019219,0.036727,0.022783,0.023278,0.025756,0.001423,0.019780,0.011846,0.074761
museum malang tempo doeloe,0.286915,0.088477,0.058566,0.301080,0.000000,0.000000,0.000000,0.000000,0.000000,0.184602,...,0.322533,0.029867,0.026136,0.000000,0.000000,0.052533,0.000000,0.054646,0.000000,0.000000
nusa dua beach,0.000000,0.028176,0.000000,0.000000,0.005727,0.000000,0.000000,0.000000,0.220938,0.000000,...,0.000000,0.019032,0.226224,0.250041,0.168308,0.024845,0.221119,0.004300,0.226100,0.018091
ramayana ballet at prambanan,0.000000,0.061240,0.020221,0.000000,0.055849,0.000000,0.000000,0.078620,0.017662,0.124275,...,0.000000,0.000000,0.035686,0.018886,0.001456,0.000000,0.018659,0.000000,0.001255,0.000000
ratu boko temple,0.000000,0.042810,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018798,0.000000,...,0.000000,0.000000,0.013430,0.004450,0.006261,0.000000,0.021098,0.000000,0.001661,0.000000
sacred monkey forest sanctuary,0.001167,0.040947,0.012100,0.009698,0.004812,0.014050,0.003616,0.002117,0.294457,0.021654,...,0.005187,0.036201,0.350955,0.577077,0.397706,0.017697,0.329973,0.016032,0.385401,0.043477
sanur beach,0.031836,0.040954,0.024236,0.016430,0.000000,0.000000,0.002874,0.000000,0.249985,0.047526,...,0.000000,0.050224,0.242111,0.294722,0.208171,0.007099,0.221014,0.001615,0.288573,0.037581
seminyak beach,0.000000,0.045661,0.000000,0.000000,0.018917,0.026940,0.000000,0.000000,0.268266,0.033703,...,0.000000,0.022231,0.297568,0.302367,0.232468,0.028316,0.246484,0.018541,0.289757,0.048105
sempu island,0.314673,0.114146,0.074984,0.341594,0.000000,0.000000,0.000000,0.000000,0.018452,0.202499,...,1.000000,0.000000,0.037151,0.006907,0.000000,0.018448,0.016304,0.000000,0.006704,0.000000
sewu temple,0.000000,0.057548,0.020553,0.000000,0.045413,0.000000,0.000000,0.000000,0.004683,0.029722,...,0.000000,1.000000,0.019634,0.043651,0.012579,0.000000,0.040690,0.000000,0.030945,0.000000
tanah lot temple,0.021689,0.041718,0.012480,0.022450,0.023723,0.022869,0.005485,0.010436,0.270101,0.057326,...,0.037151,0.019634,1.000000,0.349070,0.248446,0.023580,0.444781,0.022947,0.249204,0.049238
tegalalang rice terrace,0.018188,0.052059,0.028714,0.015905,0.000000,0.000000,0.016374,0.000000,0.298488,0.022885,...,0.006907,0.043651,0.349070,1.000000,0.428306,0.036671,0.324836,0.021650,0.301821,0.032655
tegenungan waterfall,0.000000,0.047011,0.016731,0.000000,0.026374,0.020802,0.006098,0.000000,0.208723,0.010622,...,0.000000,0.012579,0.248446,0.428306,1.000000,0.023984,0.229099,0.001523,0.226889,0.024194
ullen sentalu museum,0.000000,0.059316,0.043036,0.021784,0.027814,0.000000,0.000000,0.030119,0.009708,0.016803,...,0.018448,0.000000,0.023580,0.036671,0.023984,1.000000,0.016896,0.000000,0.005772,0.000000
uluwatu temple,0.011467,0.041664,0.022440,0.013637,0.017018,0.019389,0.011368,0.007487,0.235879,0.028463,...,0.016304,0.040690,0.444781,0.324836,0.229099,0.016896,1.000000,0.015970,0.250949,0.034166
water castle (tamansari),0.045348,0.033844,0.037605,0.000000,0.058423,0.000000,0.000000,0.000000,0.035345,0.007647,...,0.000000,0.000000,0.022947,0.021650,0.001523,0.000000,0.015970,1.000000,0.006567,0.000000
waterbom bali,0.005516,0.021173,0.001408,0.003340,0.006998,0.009965,0.004674,0.000000,0.319311,0.000000,...,0.006704,0.030945,0.249204,0.301821,0.226889,0.005772,0.250949,0.006567,1.000000,0.026552
yogyakarta palace,0.000000,0.069044,0.013576,0.000000,0.037496,0.000000,0.000000,0.013196,0.031449,0.090799,...,0.000000,0.000000,0.049238,0.032655,0.024194,0.000000,0.034166,0.000000,0.026552,1.000000

In [21]:
import re
def recemmond(data,desc,attractioncity):
    desc=re.sub("[^a-zA-Z0-9]"," ",desc).lower().strip()
    reccomend=attraction_attraction_similarity_df[desc].sort_values(ascending=False)[1:6]
    reccom=[]
    data=data[data.attractioncity.str.lower()==attractioncity.lower()]
    for i in reccomend.index:
        reccom.append(i)
    result=data[data.attraction.str.lower().isin(reccom)].drop_duplicates(keep="first",subset="attraction").loc[:,["attraction","attractionaddress","ratingx"]].sort_values(by="ratingx",ascending=False).reset_index(drop=True)
    return result

In [22]:
recemmond(data,"@@@Sacred Monkey Forest Sanctuary !!!!","douala")

,attraction,attractionaddress,ratingx
0,Tegalalang Rice Terrace,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",5
1,Waterbom Bali,"Jl. Kartika Plaza, Kuta 80361 Indonesia",5
2,Uluwatu Temple,"Jl. Raya Uluwatu Southern part of Bali, Pecatu...",5
3,Tegenungan Waterfall,"Jl. Raya Tegenungan, Kemenuh, Ubud 80581 Indon...",5
4,Tanah Lot Temple,"Kecamatan Kediri, Kabupaten Tabanan, Beraban 8...",3

In [23]:
res=attraction_attraction_similarity_df["tegenungan waterfall"].sort_values(ascending=False)[1:6]
res

attraction
tegalalang rice terrace           0.428306
sacred monkey forest sanctuary    0.397706
tanah lot temple                  0.248446
seminyak beach                    0.232468
uluwatu temple                    0.229099
Name: tegenungan waterfall, dtype: float64

In [24]:
result=[]
for i in res.index:
    result.append(i)
result

['tegalalang rice terrace',
 'sacred monkey forest sanctuary',
 'tanah lot temple',
 'seminyak beach',
 'uluwatu temple']

In [25]:
recc_df=data[data.attraction.str.lower().isin(result)].drop_duplicates(keep="first",subset="attraction").reset_index(drop=True).loc[:,["attraction","attractionaddress","ratingx"]]
recc_df

,attraction,attractionaddress,ratingx
0,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",4
1,Tegalalang Rice Terrace,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",5
2,Uluwatu Temple,"Jl. Raya Uluwatu Southern part of Bali, Pecatu...",5
3,Tanah Lot Temple,"Kecamatan Kediri, Kabupaten Tabanan, Beraban 8...",3
4,Seminyak Beach,Seminyak,5